# Generated by Django 2.0.1 on 2018-04-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensusBgAoi',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('statefp', models.CharField(blank=True, max_length=2, null=True)),
                ('countyfp', models.CharField(blank=True, max_length=3, null=True)),
                ('tractce', models.CharField(blank=True, max_length=6, null=True)),
                ('blkgrpce', models.CharField(blank=True, max_length=1, null=True)),
                ('geoid', models.CharField(blank=True, max_length=12, null=True)),
                ('namelsad', models.CharField(blank=True, max_length=13, null=True)),
                ('mtfcc', models.CharField(blank=True, max_length=5, null=True)),
                ('funcstat', models.CharField(blank=True, max_length=1, null=True)),
                ('aland', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('awater', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('intptlat', models.CharField(blank=True, max_length=11, null=True)),
                ('intptlon', models.CharField(blank=True, max_length=12, null=True)),
                ('bg_areasqk', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('wkb_geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'census_bg_aoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityCenters',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('siteid', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=5, null=True)),
                ('zip4', models.CharField(blank=True, max_length=4, null=True)),
                ('county', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('web_url', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, max_length=80, null=True)),
                ('manager', models.CharField(blank=True, max_length=80, null=True)),
                ('wkb_geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'community_centers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountiesAoi',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('key', models.CharField(blank=True, max_length=32, null=True)),
                ('wkb_geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'counties_aoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.CharField(blank=True, max_length=38, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=5, null=True)),
                ('wkb_geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OregonLiquefactionSusceptibility',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('g_mrg_u_l', models.CharField(blank=True, max_length=60, null=True)),
                ('source', models.CharField(blank=True, max_length=12, null=True)),
                ('liq_susc', models.SmallIntegerField(blank=True, null=True)),
                ('shape_length', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('wkb_geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oregon_liquefaction_susceptibility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OregonNehrpSiteClass',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('g_mrg_u_l', models.CharField(blank=True, max_length=60, null=True)),
                ('source', models.CharField(blank=True, max_length=12, null=True)),
                ('nehrp_cl', models.CharField(blank=True, max_length=2, null=True)),
                ('usgs_pnw_vs30', models.SmallIntegerField(blank=True, null=True)),
                ('shape_length', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('wkb_geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oregon_nehrp_site_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OregonVsMeasurementIntervals',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.CharField(blank=True, max_length=15, null=True)),
                ('from_m', models.FloatField(blank=True, null=True)),
                ('depth_to_m', models.FloatField(blank=True, null=True)),
                ('vs_m_sec', models.FloatField(blank=True, null=True)),
                ('reptd_lith', models.CharField(blank=True, max_length=15, null=True)),
                ('ogdc_gmrge', models.CharField(blank=True, max_length=25, null=True)),
                ('vsbest', models.CharField(blank=True, max_length=25, null=True)),
                ('vsi_sec', models.FloatField(blank=True, null=True)),
                ('orlamx', models.FloatField(blank=True, null=True)),
                ('orlamy', models.FloatField(blank=True, null=True)),
                ('interval', models.FloatField(blank=True, null=True)),
                ('wkb_geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oregon_vs_measurement_intervals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OregonVsMeasurementSites',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.CharField(blank=True, max_length=15, null=True)),
                ('orlam_x', models.FloatField(blank=True, null=True)),
                ('orlam_y', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=35, null=True)),
                ('depth_ft', models.FloatField(blank=True, null=True)),
                ('depth_m', models.FloatField(blank=True, null=True)),
                ('surfunit', models.CharField(blank=True, max_length=35, null=True)),
                ('vs_type', models.CharField(blank=True, max_length=10, null=True)),
                ('wkb_geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oregon_vs_measurement_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubstationPortland',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('averagexfm', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('wkb_geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'substation_portland',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnreinforcedMasonryBuildings',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('propkey', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('data_sourc', models.CharField(blank=True, max_length=80, null=True)),
                ('demolished', models.CharField(blank=True, max_length=80, null=True)),
                ('upgraded', models.CharField(blank=True, max_length=80, null=True)),
                ('upgrade_da', models.CharField(blank=True, max_length=80, null=True)),
                ('upgrade_st', models.CharField(blank=True, max_length=80, null=True)),
                ('upgrade_pe', models.CharField(blank=True, max_length=80, null=True)),
                ('upgrade_1', models.CharField(blank=True, db_column='upgrade__1', max_length=254, null=True)),
                ('partial_up', models.CharField(blank=True, max_length=80, null=True)),
                ('phased_sei', models.CharField(blank=True, max_length=80, null=True)),
                ('quarter_se', models.CharField(blank=True, max_length=80, null=True)),
                ('wall_type', models.CharField(blank=True, max_length=80, null=True)),
                ('bldg_use', models.CharField(blank=True, max_length=80, null=True)),
                ('primary_oc', models.CharField(blank=True, max_length=80, null=True)),
                ('occupancy_field', models.CharField(blank=True, db_column='occupancy_', max_length=80, null=True)),
                ('occupanc_1', models.CharField(blank=True, max_length=80, null=True)),
                ('occupanc_2', models.CharField(blank=True, max_length=80, null=True)),
                ('num_people', models.CharField(blank=True, max_length=80, null=True)),
                ('num_storie', models.CharField(blank=True, max_length=80, null=True)),
                ('floor_sq_f', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('year_built', models.CharField(blank=True, max_length=80, null=True)),
                ('vacant', models.CharField(blank=True, max_length=80, null=True)),
                ('reviewed_d', models.CharField(blank=True, max_length=80, null=True)),
                ('verified_d', models.CharField(blank=True, max_length=80, null=True)),
                ('liquefacti', models.CharField(blank=True, max_length=80, null=True)),
                ('property_c', models.CharField(blank=True, max_length=80, null=True)),
                ('units', models.CharField(blank=True, max_length=80, null=True)),
                ('demo_permi', models.CharField(blank=True, max_length=80, null=True)),
                ('bldg_name', models.CharField(blank=True, max_length=113, null=True)),
                ('city_owned', models.CharField(blank=True, max_length=80, null=True)),
                ('bps_bldg_i', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('urm_class', models.CharField(blank=True, max_length=80, null=True)),
                ('city_finan', models.CharField(blank=True, max_length=80, null=True)),
                ('city_inter', models.CharField(blank=True, max_length=80, null=True)),
                ('historic_b', models.CharField(blank=True, max_length=80, null=True)),
                ('hri_rank', models.CharField(blank=True, max_length=80, null=True)),
                ('hri_name', models.CharField(blank=True, max_length=80, null=True)),
                ('conservati', models.CharField(blank=True, max_length=80, null=True)),
                ('historic_d', models.CharField(blank=True, max_length=80, null=True)),
                ('local_land', models.CharField(blank=True, max_length=80, null=True)),
                ('conserva_1', models.CharField(blank=True, max_length=80, null=True)),
                ('contributi', models.CharField(blank=True, max_length=80, null=True)),
                ('national_l', models.CharField(blank=True, max_length=80, null=True)),
                ('historic_s', models.CharField(blank=True, max_length=80, null=True)),
                ('shapestare', models.DecimalField(blank=True, decimal_places=15, max_digits=24, null=True)),
                ('shapestlen', models.DecimalField(blank=True, decimal_places=15, max_digits=24, null=True)),
                ('wkb_geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unreinforced_masonry_buildings',
                'managed': False,
            },
        ),
    ]
