-- View: public.quake_loss_view

-- DROP VIEW public.quake_loss_view;

CREATE OR REPLACE VIEW public.quake_loss_view AS 
 SELECT
    loss_jurisdiction_csz_m9p0_dry.objectid,
    'csz_m9p0'::text as quake_cd,
    'dry'::text as condition_cd,
    'jurisdiction'::text as area_type_cd,
    loss_jurisdiction_csz_m9p0_dry.jurisdiction,
    0 AS nuid,
    loss_jurisdiction_csz_m9p0_dry.bldgloss,
    loss_jurisdiction_csz_m9p0_dry.bldg_lr,
    loss_jurisdiction_csz_m9p0_dry.contentloss,
    loss_jurisdiction_csz_m9p0_dry.debris,
    loss_jurisdiction_csz_m9p0_dry.displacedpop,
    loss_jurisdiction_csz_m9p0_dry.casdaytotal,
    loss_jurisdiction_csz_m9p0_dry.casdayl1,
    loss_jurisdiction_csz_m9p0_dry.casdayl2,
    loss_jurisdiction_csz_m9p0_dry.casdayl3,
    loss_jurisdiction_csz_m9p0_dry.casdayl4,
    loss_jurisdiction_csz_m9p0_dry.casnighttotal,
    loss_jurisdiction_csz_m9p0_dry.casnightl1,
    loss_jurisdiction_csz_m9p0_dry.casnightl2,
    loss_jurisdiction_csz_m9p0_dry.casnightl3,
    loss_jurisdiction_csz_m9p0_dry.casnightl4,
    loss_jurisdiction_csz_m9p0_dry.pdsnone,
    loss_jurisdiction_csz_m9p0_dry.pdsslight,
    loss_jurisdiction_csz_m9p0_dry.pdsmoderate,
    loss_jurisdiction_csz_m9p0_dry.pdsextensive,
    loss_jurisdiction_csz_m9p0_dry.pdscomplete
   FROM loss_jurisdiction_csz_m9p0_dry
UNION
 SELECT
    loss_jurisdiction_csz_m9p0_wet.objectid,
    'csz_m9p0'::text as quake_cd,
    'wet'::text as condition_cd,
    'jurisdiction'::text as area_type_cd,
    loss_jurisdiction_csz_m9p0_wet.jurisdiction,
    0 AS nuid,
    loss_jurisdiction_csz_m9p0_wet.bldgloss,
    loss_jurisdiction_csz_m9p0_wet.bldg_lr,
    loss_jurisdiction_csz_m9p0_wet.contentloss,
    loss_jurisdiction_csz_m9p0_wet.debris,
    loss_jurisdiction_csz_m9p0_wet.displacedpop,
    loss_jurisdiction_csz_m9p0_wet.casdaytotal,
    loss_jurisdiction_csz_m9p0_wet.casdayl1,
    loss_jurisdiction_csz_m9p0_wet.casdayl2,
    loss_jurisdiction_csz_m9p0_wet.casdayl3,
    loss_jurisdiction_csz_m9p0_wet.casdayl4,
    loss_jurisdiction_csz_m9p0_wet.casnighttotal,
    loss_jurisdiction_csz_m9p0_wet.casnightl1,
    loss_jurisdiction_csz_m9p0_wet.casnightl2,
    loss_jurisdiction_csz_m9p0_wet.casnightl3,
    loss_jurisdiction_csz_m9p0_wet.casnightl4,
    loss_jurisdiction_csz_m9p0_wet.pdsnone,
    loss_jurisdiction_csz_m9p0_wet.pdsslight,
    loss_jurisdiction_csz_m9p0_wet.pdsmoderate,
    loss_jurisdiction_csz_m9p0_wet.pdsextensive,
    loss_jurisdiction_csz_m9p0_wet.pdscomplete
   FROM loss_jurisdiction_csz_m9p0_wet
UNION
 SELECT
    loss_jurisdiction_phf_m6p8_dry.objectid,
    'phf_m6p8'::text as quake_cd,
    'dry'::text as condition_cd,
    'jurisdiction'::text as area_type_cd,
    loss_jurisdiction_phf_m6p8_dry.jurisdiction,
    0 AS nuid,
    loss_jurisdiction_phf_m6p8_dry.bldgloss,
    loss_jurisdiction_phf_m6p8_dry.bldg_lr,
    loss_jurisdiction_phf_m6p8_dry.contentloss,
    loss_jurisdiction_phf_m6p8_dry.debris,
    loss_jurisdiction_phf_m6p8_dry.displacedpop,
    loss_jurisdiction_phf_m6p8_dry.casdaytotal,
    loss_jurisdiction_phf_m6p8_dry.casdayl1,
    loss_jurisdiction_phf_m6p8_dry.casdayl2,
    loss_jurisdiction_phf_m6p8_dry.casdayl3,
    loss_jurisdiction_phf_m6p8_dry.casdayl4,
    loss_jurisdiction_phf_m6p8_dry.casnighttotal,
    loss_jurisdiction_phf_m6p8_dry.casnightl1,
    loss_jurisdiction_phf_m6p8_dry.casnightl2,
    loss_jurisdiction_phf_m6p8_dry.casnightl3,
    loss_jurisdiction_phf_m6p8_dry.casnightl4,
    loss_jurisdiction_phf_m6p8_dry.pdsnone,
    loss_jurisdiction_phf_m6p8_dry.pdsslight,
    loss_jurisdiction_phf_m6p8_dry.pdsmoderate,
    loss_jurisdiction_phf_m6p8_dry.pdsextensive,
    loss_jurisdiction_phf_m6p8_dry.pdscomplete
   FROM loss_jurisdiction_phf_m6p8_dry
UNION
 SELECT
    loss_jurisdiction_phf_m6p8_wet.objectid,
    'phf_m6p8'::text as quake_cd,
    'wet'::text as condition_cd,
    'jurisdiction'::text as area_type_cd,
    loss_jurisdiction_phf_m6p8_wet.jurisdiction,
    0 AS nuid,
    loss_jurisdiction_phf_m6p8_wet.bldgloss,
    loss_jurisdiction_phf_m6p8_wet.bldg_lr,
    loss_jurisdiction_phf_m6p8_wet.contentloss,
    loss_jurisdiction_phf_m6p8_wet.debris,
    loss_jurisdiction_phf_m6p8_wet.displacedpop,
    loss_jurisdiction_phf_m6p8_wet.casdaytotal,
    loss_jurisdiction_phf_m6p8_wet.casdayl1,
    loss_jurisdiction_phf_m6p8_wet.casdayl2,
    loss_jurisdiction_phf_m6p8_wet.casdayl3,
    loss_jurisdiction_phf_m6p8_wet.casdayl4,
    loss_jurisdiction_phf_m6p8_wet.casnighttotal,
    loss_jurisdiction_phf_m6p8_wet.casnightl1,
    loss_jurisdiction_phf_m6p8_wet.casnightl2,
    loss_jurisdiction_phf_m6p8_wet.casnightl3,
    loss_jurisdiction_phf_m6p8_wet.casnightl4,
    loss_jurisdiction_phf_m6p8_wet.pdsnone,
    loss_jurisdiction_phf_m6p8_wet.pdsslight,
    loss_jurisdiction_phf_m6p8_wet.pdsmoderate,
    loss_jurisdiction_phf_m6p8_wet.pdsextensive,
    loss_jurisdiction_phf_m6p8_wet.pdscomplete
   FROM loss_jurisdiction_phf_m6p8_wet
UNION
 SELECT
    loss_neighborhood_unit_csz_m9p0_dry.objectid,
    'csz_m9p0'::text as quake_cd,
    'dry'::text as condition_cd,
    'neighborhood_unit'::text as area_type_cd,
    ''::character varying AS jurisdiction,
    loss_neighborhood_unit_csz_m9p0_dry.nuid,
    loss_neighborhood_unit_csz_m9p0_dry.bldgloss,
    loss_neighborhood_unit_csz_m9p0_dry.bldg_lr,
    loss_neighborhood_unit_csz_m9p0_dry.contentloss,
    loss_neighborhood_unit_csz_m9p0_dry.debris,
    loss_neighborhood_unit_csz_m9p0_dry.displacedpop,
    loss_neighborhood_unit_csz_m9p0_dry.casdaytotal,
    loss_neighborhood_unit_csz_m9p0_dry.casdayl1,
    loss_neighborhood_unit_csz_m9p0_dry.casdayl2,
    loss_neighborhood_unit_csz_m9p0_dry.casdayl3,
    loss_neighborhood_unit_csz_m9p0_dry.casdayl4,
    loss_neighborhood_unit_csz_m9p0_dry.casnighttotal,
    loss_neighborhood_unit_csz_m9p0_dry.casnightl1,
    loss_neighborhood_unit_csz_m9p0_dry.casnightl2,
    loss_neighborhood_unit_csz_m9p0_dry.casnightl3,
    loss_neighborhood_unit_csz_m9p0_dry.casnightl4,
    loss_neighborhood_unit_csz_m9p0_dry.pdsnone,
    loss_neighborhood_unit_csz_m9p0_dry.pdsslight,
    loss_neighborhood_unit_csz_m9p0_dry.pdsmoderate,
    loss_neighborhood_unit_csz_m9p0_dry.pdsextensive,
    loss_neighborhood_unit_csz_m9p0_dry.pdscomplete
   FROM loss_neighborhood_unit_csz_m9p0_dry
UNION
 SELECT
    loss_neighborhood_unit_csz_m9p0_wet.objectid,
    'csz_m9p0'::text as quake_cd,
    'wet'::text as condition_cd,
    'neighborhood_unit'::text as area_type_cd,
    ''::character varying AS jurisdiction,
    loss_neighborhood_unit_csz_m9p0_wet.nuid,
    loss_neighborhood_unit_csz_m9p0_wet.bldgloss,
    loss_neighborhood_unit_csz_m9p0_wet.bldg_lr,
    loss_neighborhood_unit_csz_m9p0_wet.contentloss,
    loss_neighborhood_unit_csz_m9p0_wet.debris,
    loss_neighborhood_unit_csz_m9p0_wet.displacedpop,
    loss_neighborhood_unit_csz_m9p0_wet.casdaytotal,
    loss_neighborhood_unit_csz_m9p0_wet.casdayl1,
    loss_neighborhood_unit_csz_m9p0_wet.casdayl2,
    loss_neighborhood_unit_csz_m9p0_wet.casdayl3,
    loss_neighborhood_unit_csz_m9p0_wet.casdayl4,
    loss_neighborhood_unit_csz_m9p0_wet.casnighttotal,
    loss_neighborhood_unit_csz_m9p0_wet.casnightl1,
    loss_neighborhood_unit_csz_m9p0_wet.casnightl2,
    loss_neighborhood_unit_csz_m9p0_wet.casnightl3,
    loss_neighborhood_unit_csz_m9p0_wet.casnightl4,
    loss_neighborhood_unit_csz_m9p0_wet.pdsnone,
    loss_neighborhood_unit_csz_m9p0_wet.pdsslight,
    loss_neighborhood_unit_csz_m9p0_wet.pdsmoderate,
    loss_neighborhood_unit_csz_m9p0_wet.pdsextensive,
    loss_neighborhood_unit_csz_m9p0_wet.pdscomplete
   FROM loss_neighborhood_unit_csz_m9p0_wet
UNION
 SELECT
    loss_neighborhood_unit_phf_m6p8_dry.objectid,
    'phf_m6p8'::text as quake_cd,
    'dry'::text as condition_cd,
    'neighborhood_unit'::text as area_type_cd,
    ''::character varying AS jurisdiction,
    loss_neighborhood_unit_phf_m6p8_dry.nuid,
    loss_neighborhood_unit_phf_m6p8_dry.bldgloss,
    loss_neighborhood_unit_phf_m6p8_dry.bldg_lr,
    loss_neighborhood_unit_phf_m6p8_dry.contentloss,
    loss_neighborhood_unit_phf_m6p8_dry.debris,
    loss_neighborhood_unit_phf_m6p8_dry.displacedpop,
    loss_neighborhood_unit_phf_m6p8_dry.casdaytotal,
    loss_neighborhood_unit_phf_m6p8_dry.casdayl1,
    loss_neighborhood_unit_phf_m6p8_dry.casdayl2,
    loss_neighborhood_unit_phf_m6p8_dry.casdayl3,
    loss_neighborhood_unit_phf_m6p8_dry.casdayl4,
    loss_neighborhood_unit_phf_m6p8_dry.casnighttotal,
    loss_neighborhood_unit_phf_m6p8_dry.casnightl1,
    loss_neighborhood_unit_phf_m6p8_dry.casnightl2,
    loss_neighborhood_unit_phf_m6p8_dry.casnightl3,
    loss_neighborhood_unit_phf_m6p8_dry.casnightl4,
    loss_neighborhood_unit_phf_m6p8_dry.pdsnone,
    loss_neighborhood_unit_phf_m6p8_dry.pdsslight,
    loss_neighborhood_unit_phf_m6p8_dry.pdsmoderate,
    loss_neighborhood_unit_phf_m6p8_dry.pdsextensive,
    loss_neighborhood_unit_phf_m6p8_dry.pdscomplete
   FROM loss_neighborhood_unit_phf_m6p8_dry
UNION
 SELECT
    loss_neighborhood_unit_phf_m6p8_wet.objectid,
    'phf_m6p8'::text as quake_cd,
    'dry'::text as condition_cd,
    'neighborhood_unit'::text as area_type_cd,
    ''::character varying AS jurisdiction,
    loss_neighborhood_unit_phf_m6p8_wet.nuid,
    loss_neighborhood_unit_phf_m6p8_wet.bldgloss,
    loss_neighborhood_unit_phf_m6p8_wet.bldg_lr,
    loss_neighborhood_unit_phf_m6p8_wet.contentloss,
    loss_neighborhood_unit_phf_m6p8_wet.debris,
    loss_neighborhood_unit_phf_m6p8_wet.displacedpop,
    loss_neighborhood_unit_phf_m6p8_wet.casdaytotal,
    loss_neighborhood_unit_phf_m6p8_wet.casdayl1,
    loss_neighborhood_unit_phf_m6p8_wet.casdayl2,
    loss_neighborhood_unit_phf_m6p8_wet.casdayl3,
    loss_neighborhood_unit_phf_m6p8_wet.casdayl4,
    loss_neighborhood_unit_phf_m6p8_wet.casnighttotal,
    loss_neighborhood_unit_phf_m6p8_wet.casnightl1,
    loss_neighborhood_unit_phf_m6p8_wet.casnightl2,
    loss_neighborhood_unit_phf_m6p8_wet.casnightl3,
    loss_neighborhood_unit_phf_m6p8_wet.casnightl4,
    loss_neighborhood_unit_phf_m6p8_wet.pdsnone,
    loss_neighborhood_unit_phf_m6p8_wet.pdsslight,
    loss_neighborhood_unit_phf_m6p8_wet.pdsmoderate,
    loss_neighborhood_unit_phf_m6p8_wet.pdsextensive,
    loss_neighborhood_unit_phf_m6p8_wet.pdscomplete
   FROM loss_neighborhood_unit_phf_m6p8_wet;

ALTER TABLE public.quake_loss_view
  OWNER TO "disaster-resilience";

GRANT ALL ON TABLE public."quake_loss_view" TO "disaster-resilience";
GRANT SELECT ON TABLE public."quake_loss_view" TO "disaster-resilience-readonly";

